CREATE TABLE ApiKeys (
    Id SERIAL PRIMARY KEY,
    ClientName VARCHAR(100) NOT NULL,
    HashedKey VARCHAR(256) NOT NULL UNIQUE,
    IsEnabled BOOLEAN NOT NULL DEFAULT TRUE,
    CreatedById INT NOT NULL,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ExpiresAt TIMESTAMP NULL,
    CONSTRAINT FK_ApiKeys_Administrators FOREIGN KEY (CreatedById) REFERENCES Administrators(Id)
);
