CREATE TABLE Users (
    Id VARCHAR(26) PRIMARY KEY,
    Username VARCHAR(100) NOT NULL UNIQUE,
    Password VARCHAR(256) NOT NULL,
    FullName VARCHAR(200) NOT NULL,
    ProfileImageUrl VARCHAR(500),
    Role VARCHAR(50) NOT NULL DEFAULT 'User',
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
